{{- range $serviceName, $serviceData := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ $serviceName }}
spec:
  replicas: {{ $serviceData.replicas }}
  selector:
    matchLabels:
      app: {{ $serviceName }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: {{ $serviceName }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: {{ $serviceName }}
        securityContext:
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
        workingDir: /app/services/{{ $serviceName }}
        command: ["node", "src/index.js"]
        ports:
        - containerPort: {{ $serviceData.port }}
        livenessProbe:
          tcpSocket:
            port: {{ $serviceData.port }}
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: {{ $serviceData.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: PORT
          value: "{{ $serviceData.port }}"
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: db-secrets-aws
              key: POSTGRES_HOST
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets-aws
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets-aws
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-secrets-aws
              key: POSTGRES_DB
{{- range $otherServiceName, $otherServiceData := $.Values.services }}
        - name: {{ $otherServiceName | upper | replace "-" "_" }}_URL
          value: "http://{{ $otherServiceName }}:{{ $otherServiceData.port }}"
{{- end }}
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 150m
            memory: 128Mi
{{- end }}
