apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-north-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secrets-external
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: db-secrets-aws # We create a new secret to not clash with the old one during migration
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_HOST
    remoteRef:
      key: student-mgmt-db-secrets
      property: DB_HOST
  - secretKey: POSTGRES_USER
    remoteRef:
      key: student-mgmt-db-secrets
      property: DB_USER
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: student-mgmt-db-secrets
      property: DB_PASSWORD
  - secretKey: POSTGRES_DB
    remoteRef:
      key: student-mgmt-db-secrets
      property: DB_NAME
