apiVersion: batch/v1
kind: CronJob
metadata:
  name: grafana-report-generator
  namespace: monitoring
spec:
  schedule: "0 8 * * *" # Run daily at 8:00 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: selenium-reporter
            image: 355878729662.dkr.ecr.eu-north-1.amazonaws.com/student-management-app:reporter
            env:
            - name: GRAFANA_URL
              value: "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local"
            - name: GRAFANA_USER
              value: "admin"
            - name: GRAFANA_PASSWORD
              value: "prom-operator"
          restartPolicy: OnFailure
