services:
  auth-service:
    port: 3005
    replicas: 1
  billing-service:
    port: 3003
    replicas: 1
  course-service:
    port: 3001
    replicas: 1
  enrollment-service:
    port: 3002
    replicas: 1
  notification-service:
    port: 3004
    replicas: 1
  student-service:
    port: 3000
    replicas: 1

image:
  repository: 355878729662.dkr.ecr.eu-north-1.amazonaws.com/student-management-app
  tag: latest

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: api.13.53.93.82.nip.io
  tls:
    - secretName: api-tls
      hosts:
        - api.13.53.93.82.nip.io
